version: '3'

services:

  truffle:
    build: .
    image: truffle
    command: 'ganache-cli --gasLimit 12530149 --mnemonic "PACT PACT PACT PACT PACT PACT PACT PACT PACT PACT PACT PACT" --host 0.0.0.0'
    volumes:
      - .:/app
    ports: 
      - "127.0.0.1:8545:8545"

